// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlYrqDEBIwP-yUlsDGjz4uJoA9Yn_dGb4',
    appId: '1:162330381857:web:a7d16b5f940a355f9f5d60',
    messagingSenderId: '162330381857',
    projectId: 'sos-project-773fa',
    authDomain: 'sos-project-773fa.firebaseapp.com',
    storageBucket: 'sos-project-773fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0UKzy1oRKI51GPZBMVE-qhJFspszrVAg',
    appId: '1:162330381857:android:f0bcd369bb72086c9f5d60',
    messagingSenderId: '162330381857',
    projectId: 'sos-project-773fa',
    storageBucket: 'sos-project-773fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqjCZitC-7vFc4p985gCsp9tJ8l3miAg4',
    appId: '1:162330381857:ios:0cd48e936e14d7ba9f5d60',
    messagingSenderId: '162330381857',
    projectId: 'sos-project-773fa',
    storageBucket: 'sos-project-773fa.appspot.com',
    iosBundleId: 'com.example.sosApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqjCZitC-7vFc4p985gCsp9tJ8l3miAg4',
    appId: '1:162330381857:ios:14f1ae374cec83839f5d60',
    messagingSenderId: '162330381857',
    projectId: 'sos-project-773fa',
    storageBucket: 'sos-project-773fa.appspot.com',
    iosBundleId: 'com.example.sosApplication.RunnerTests',
  );
}
